export default {
  login: 'bryanlou',
  id: 6599979,
  node_id: 'MDQ6VXNlcjY1OTk5Nzk=',
  avatar_url: 'https://avatars2.githubusercontent.com/u/6599979?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/bryanlou',
  html_url: 'https://github.com/bryanlou',
  followers_url: 'https://api.github.com/users/bryanlou/followers',
  following_url: 'https://api.github.com/users/bryanlou/following{/other_user}',
  gists_url: 'https://api.github.com/users/bryanlou/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/bryanlou/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/bryanlou/subscriptions',
  organizations_url: 'https://api.github.com/users/bryanlou/orgs',
  repos_url: 'https://api.github.com/users/bryanlou/repos',
  events_url: 'https://api.github.com/users/bryanlou/events{/privacy}',
  received_events_url: 'https://api.github.com/users/bryanlou/received_events',
  type: 'User',
  site_admin: false,
  name: 'Bryan Lou',
  company: '@uber ',
  blog: 'https://bryanlou.com',
  location: 'San Francisco, CA',
  email: null,
  hireable: true,
  bio: null,
  public_repos: 53,
  public_gists: 4,
  followers: 248,
  following: 12,
  created_at: '2014-02-05T23:22:59Z',
  updated_at: '2019-04-17T03:18:31Z',
};
