export default [
  {
    id: 190296121,
    node_id: 'MDEwOlJlcG9zaXRvcnkxOTAyOTYxMjE=',
    name: 'octohub',
    full_name: 'bryanlou/octohub',
    private: false,
    owner: {
      login: 'bryanlou',
      id: 6599979,
      node_id: 'MDQ6VXNlcjY1OTk5Nzk=',
      avatar_url: 'https://avatars2.githubusercontent.com/u/6599979?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/bryanlou',
      html_url: 'https://github.com/bryanlou',
      followers_url: 'https://api.github.com/users/bryanlou/followers',
      following_url: 'https://api.github.com/users/bryanlou/following{/other_user}',
      gists_url: 'https://api.github.com/users/bryanlou/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/bryanlou/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/bryanlou/subscriptions',
      organizations_url: 'https://api.github.com/users/bryanlou/orgs',
      repos_url: 'https://api.github.com/users/bryanlou/repos',
      events_url: 'https://api.github.com/users/bryanlou/events{/privacy}',
      received_events_url: 'https://api.github.com/users/bryanlou/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/bryanlou/octohub',
    description: 'A different, new look at your GitHub Profile',
    fork: false,
    url: 'https://api.github.com/repos/bryanlou/octohub',
    forks_url: 'https://api.github.com/repos/bryanlou/octohub/forks',
    keys_url: 'https://api.github.com/repos/bryanlou/octohub/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/bryanlou/octohub/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/bryanlou/octohub/teams',
    hooks_url: 'https://api.github.com/repos/bryanlou/octohub/hooks',
    issue_events_url: 'https://api.github.com/repos/bryanlou/octohub/issues/events{/number}',
    events_url: 'https://api.github.com/repos/bryanlou/octohub/events',
    assignees_url: 'https://api.github.com/repos/bryanlou/octohub/assignees{/user}',
    branches_url: 'https://api.github.com/repos/bryanlou/octohub/branches{/branch}',
    tags_url: 'https://api.github.com/repos/bryanlou/octohub/tags',
    blobs_url: 'https://api.github.com/repos/bryanlou/octohub/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/bryanlou/octohub/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/bryanlou/octohub/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/bryanlou/octohub/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/bryanlou/octohub/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/bryanlou/octohub/languages',
    stargazers_url: 'https://api.github.com/repos/bryanlou/octohub/stargazers',
    contributors_url: 'https://api.github.com/repos/bryanlou/octohub/contributors',
    subscribers_url: 'https://api.github.com/repos/bryanlou/octohub/subscribers',
    subscription_url: 'https://api.github.com/repos/bryanlou/octohub/subscription',
    commits_url: 'https://api.github.com/repos/bryanlou/octohub/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/bryanlou/octohub/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/bryanlou/octohub/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/bryanlou/octohub/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/bryanlou/octohub/contents/{+path}',
    compare_url: 'https://api.github.com/repos/bryanlou/octohub/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/bryanlou/octohub/merges',
    archive_url: 'https://api.github.com/repos/bryanlou/octohub/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/bryanlou/octohub/downloads',
    issues_url: 'https://api.github.com/repos/bryanlou/octohub/issues{/number}',
    pulls_url: 'https://api.github.com/repos/bryanlou/octohub/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/bryanlou/octohub/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/bryanlou/octohub/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/bryanlou/octohub/labels{/name}',
    releases_url: 'https://api.github.com/repos/bryanlou/octohub/releases{/id}',
    deployments_url: 'https://api.github.com/repos/bryanlou/octohub/deployments',
    created_at: '2019-06-04T23:58:30Z',
    updated_at: '2019-06-15T21:12:31Z',
    pushed_at: '2019-06-15T21:12:30Z',
    git_url: 'git://github.com/bryanlou/octohub.git',
    ssh_url: 'git@github.com:bryanlou/octohub.git',
    clone_url: 'https://github.com/bryanlou/octohub.git',
    svn_url: 'https://github.com/bryanlou/octohub',
    homepage: 'https://octohub.bryanlou.now.sh/',
    size: 7609,
    stargazers_count: 6,
    watchers_count: 6,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    forks: 0,
    open_issues: 0,
    watchers: 6,
    default_branch: 'master',
  },

];
